# Generated by Django 4.1.7 on 2023-11-12 19:26

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("keywords", models.CharField(max_length=500)),
                ("company", models.CharField(default="", max_length=500)),
                ("sdescription", models.CharField(max_length=500)),
                ("description", ckeditor.fields.RichTextField()),
                ("background_img_url", models.CharField(max_length=500)),
                ("logo_img_url", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=500)),
                ("eemail", models.CharField(max_length=500)),
                ("expire_in_days", models.DateField()),
                (
                    "time",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                ("posted_by", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("email", models.CharField(max_length=500, unique=True)),
                ("username", models.CharField(max_length=500)),
                ("password", models.CharField(max_length=500)),
                ("company", models.CharField(max_length=500)),
                ("job", models.CharField(max_length=500)),
                ("account_locked", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("subscriber", models.BooleanField(default=True)),
                ("subscriber_id", models.CharField(default="", max_length=500)),
                ("key", models.CharField(max_length=500)),
                (
                    "img_url",
                    models.CharField(
                        default="https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
