# Generated by Django 4.1.7 on 2023-11-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_profiles_last_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="time",
            field=models.FloatField(default=0),
        ),
    ]
