# Generated by Django 4.1.7 on 2023-11-12 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_remove_profiles_last_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="last_attempt",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
