# Generated by Django 4.1.7 on 2023-11-12 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0005_profiles_last_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="time",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="last_attempt",
            field=models.FloatField(default=0),
        ),
    ]
