# Generated by Django 4.1.7 on 2023-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0006_alter_jobs_time_alter_profiles_last_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="otp",
            field=models.CharField(default="", max_length=500),
        ),
    ]
