# Generated by Django 4.1.7 on 2023-11-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0007_profiles_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="salt",
            field=models.CharField(default="", max_length=500),
        ),
    ]
