# Generated by Django 4.1.7 on 2023-11-16 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0008_profiles_salt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiles",
            old_name="salt",
            new_name="Hmac",
        ),
    ]
